# Generated by Django 5.2.12 on 2026-03-18 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('convert', 'Format Convert'), ('download', 'Video Download')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('input_format', models.CharField(blank=True, max_length=20)),
                ('output_format', models.CharField(blank=True, max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('download_quality', models.CharField(default='best', max_length=20)),
                ('output_url', models.URLField(blank=True, max_length=1000)),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
